services:
  automatic1111:
    build: ./build/automatic1111
    #image: ulyssesrr/rocm-xtra-stable-diffusion-webui:1.6.0_rocm5.5.1_ubuntu22.04_pytorch2.0.1
    command: "--lowvram --enable-insecure-extension-access --api --skip-torch-cuda-test --opt-sub-quad-attention --sub-quad-q-chunk-size 512 --sub-quad-kv-chunk-size 512 --sub-quad-chunk-threshold 80 --upcast-sampling"
    # --medvram --medvram-sdxl if you have 8gb vram
    # --no-half-vae if you are not using TAESD or sdxl-vae-fp16-fix
    devices:
      - /dev/dri:/dev/dri
      - /dev/kfd:/dev/kfd
    ipc: host
    group_add: 
      - video
    cap_add:
      - SYS_ADMIN
    security_opt:
      - seccomp:unconfined
    labels:
      - "com.centurylinklabs.watchtower.enable=false"
    ports:
      - "7860:7860"
    volumes:
      - ./Automatic1111/cache:/root/.cache
      - ./Automatic1111/data:/stable-diffusion-webui/data
      - ./Automatic1111/data/embeddings:/stable-diffusion-webui/embeddings
      - ./Automatic1111/outputs:/stable-diffusion-webui/outputs
  comfyui:
    build: ./build/comfyui
    command: "--listen --port 7861 --lowvram"
    devices:
      - /dev/dri:/dev/dri
      - /dev/kfd:/dev/kfd
    ipc: host
    group_add: 
      - video
    cap_add:
      - SYS_ADMIN
    security_opt:
      - seccomp:unconfined
    labels:
      - "com.centurylinklabs.watchtower.enable=false"
    ports:
      - "7861:7861"
      - "8166:8166"
    volumes:
      - ./ComfyUI/cache:/root/.cache
      - ./ComfyUI/data:/comfyui/data
      - ./ComfyUI/data/embeddings:/comfyui/embeddings
      - ./ComfyUI/outputs:/comfyui/outputs
