version: "3.9"
services:
  automatic1111:
    build: automatic1111
    command: "--precision full --no-half --medvram --medvram-sdxl --xformers --enable-insecure-extension-access --api --opt-sdp-no-mem-attention"
    # --lowvram --always-batch-cond-uncond
    network_mode: host
    devices:
      - /dev/dri:/dev/dri
      - /dev/kfd:/dev/kfd
    ipc: host
    shm_size: "32G"
    group_add: 
      - video
    cap_add:
      - SYS_ADMIN
    seccurity_opt:
      - seccomp:unconfined
    ports:
      - "7860:7860"
    volumes:
      - ./cache:/root/.cache
      - ./data:/stable-diffusion-webui/data
      - ./data/embeddings:/stable-diffusion-webui/embeddings
      - ./outputs:/stable-diffusion-webui/outputs
  comfyui:
    build: comfyui
    network_mode: host
    devices:
      - /dev/dri:/dev/dri
      - /dev/kfd:/dev/kfd
    ipc: host
    shm_size: "32G"
    group_add: 
      - video
    cap_add:
      - SYS_ADMIN
    seccurity_opt:
      - seccomp:unconfined
    ports:
      - "7861:7861"
    volumes:
      - ./cache:/root/.cache
      - ./data:/comfyui/data
      - ./data/embeddings:/comfyui/embeddings
      - ./outputs:/comfyui/outputs
