services:
  automatic1111:
    #build: automatic1111
    image: ulyssesrr/rocm-xtra-stable-diffusion-webui:1.6.0_rocm5.5.1_ubuntu22.04_pytorch2.0.1
    command: "--medvram --enable-insecure-extension-access --api --opt-sub-quad-attention --disable-nan-check --upcast-sampling --sub-quad-q-chunk-size 512 --sub-quad-kv-chunk-size 512 --sub-quad-chunk-threshold 80 --skip-torch-cuda-test"
    # --medvram --medvram-sdxl --precision full --no-half
    devices:
      - /dev/dri:/dev/dri
      - /dev/kfd:/dev/kfd
    ipc: host
    shm_size: "32G"
    group_add: 
      - video
    cap_add:
      - SYS_ADMIN
    security_opt:
      - seccomp:unconfined
    labels:
      - "com.centurylinklabs.watchtower.enable=false"
    ports:
      - "7860:7860"
    volumes:
      - ./Automatic1111/cache:/root/.cache
      - ./Automatic1111/data:/stable-diffusion-webui/data
      - ./Automatic1111/data/embeddings:/stable-diffusion-webui/embeddings
      - ./Automatic1111/outputs:/stable-diffusion-webui/outputs
  # comfyui:
  #   build: comfyui
  #   network_mode: host
  #   devices:
  #     - /dev/dri:/dev/dri
  #     - /dev/kfd:/dev/kfd
  #   ipc: host
  #   shm_size: "32G"
  #   group_add: 
  #     - video
  #   cap_add:
  #     - SYS_ADMIN
  #   security_opt:
  #     - seccomp:unconfined
  #   labels:
  #     - "com.centurylinklabs.watchtower.enable=false"
  #   ports:
  #     - "7861:7861"
  #   volumes:
  #     - ./cache:/root/.cache
  #     - ./data:/comfyui/data
  #     - ./data/embeddings:/comfyui/embeddings
  #     - ./outputs:/comfyui/outputs
