version: "3.9"
services:
  sd:
    build: .
    network_mode: host
    devices:
      - /dev/dri:/dev/dri
      - /dev/kfd:/dev/kfd
    ipc: host
    shm_size: "16G"
    group_add: 
      - video
    cap_add:
      - SYS_ADMIN
    seccurity_opt:
      - seccomp:unconfined
    ports:
      - "7860:7860"
    volumes:
      - ./cache:/root/.cache
      - ./data:/stable-diffusion-webui/data
      - ./data/embeddings:/stable-diffusion-webui/embeddings
      - ./outputs:/stable-diffusion-webui/outputs

